<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="neos">

  <!-- Parameters -->
  <xacro:property name="base_radius" value="0.2"/>
  <xacro:property name="base_length" value="0.1"/>
  <xacro:property name="wheel_radius" value="0.05"/>
  <xacro:property name="wheel_width" value="0.02"/>
  <xacro:property name="wheel_separation" value="0.3"/>
  <xacro:property name="caster_radius" value="0.03"/>
  <xacro:property name="base_mass" value="10"/>
  <xacro:property name="wheel_mass" value="0.5"/>
  <xacro:property name="caster_mass" value="0.1"/>

  <!-- Base Link -->
  <link name="base_link">
    <visual>
      <geometry>
        <cylinder length="${base_length}" radius="${base_radius}"/>
      </geometry>
      <material name="blue">
        <color rgba="0 0 1 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${base_length}" radius="${base_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${base_mass}"/>
      <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
    </inertial>
  </link>

  <!-- Wheel Macro -->
  <xacro:macro name="wheel" params="name side">
    <link name="${name}">
      <visual>
        <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
        </geometry>
        <material name="black">
          <color rgba="0 0 0 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="${wheel_mass}"/>
        <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
      </inertial>
    </link>

    <joint name="${name}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${name}"/>
      <origin xyz="0 ${side * wheel_separation/2} -${wheel_radius/2}" rpy="1.5708 0 0"/>
      <axis xyz="0 0 1"/>
    </joint>
  </xacro:macro>

  <!-- Caster Macro -->
  <xacro:macro name="caster" params="name x_pos">
    <link name="${name}">
      <visual>
        <geometry>
          <sphere radius="${caster_radius}"/>
        </geometry>
        <material name="gray">
          <color rgba="0.5 0.5 0.5 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <sphere radius="${caster_radius}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="${caster_mass}"/>
        <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
      </inertial>
    </link>

    <joint name="${name}_joint" type="fixed">
      <parent link="base_link"/>
      <child link="${name}"/>
      <origin xyz="${x_pos} 0 -0.03" rpy="0 0 0"/>
    </joint>
  </xacro:macro>

  <!-- Create Wheels -->
  <xacro:wheel name="left_wheel" side="1"/>
  <xacro:wheel name="right_wheel" side="-1"/>

  <!-- Create Casters -->
  <xacro:caster name="front_caster" x_pos="0.15"/>
  <xacro:caster name="rear_caster" x_pos="-0.15"/>

</robot>